# Generated by Django 3.1.5 on 2021-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='SubTopic',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
